repositories:
 - name: prometheus
   url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus
    namespace: prometheus
    chart: prometheus/prometheus
    version: "27"
    set:
      - name: server.persistentVolume.enabled
        value: true
      - name: server.persistentVolume.storageClass
        value: sata
      - name: server.persistentVolume.size
        value: 10Gi
      - name: server.persistentVolume.accessModes
        values:
          - ReadWriteOnce
